title: softlink
email: whoissoftlink@gmail.com
description: softlink
baseurl: ""            # FIXED
url: "https://who-is-softlink.github.io"
icon: /assets/images/icon-512.png
twitter_username: softlink
github_username: softlink

markdown: kramdown

plugins: []

theme: null            # IMPORTANT FIX
